import Head from 'next/head';

import HomePage from '@/views/HomePage';

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <HomePage />
    </main>
  </>
);

export default Home;
